### ISSUE TITLE
Add simulation controller to reference implementation

### ISSUE THREAD

**Issue by pablo-de-andres** [materials-marketplace/standard-app-api#27] opened 2022-06-28 07:40 UTC
An initial, cleaned up version of the code used in SimPARTIX and other transformation apps that can be used by others to start up the developing process.

This will only add a minimal working version that can be further improved later on.

**Comment by csadorf** [comment] 2022-07-06 15:02
Duplicate of #20 .

**Closed by csadorf** 2022-07-06 15:02 UTC
